INSERT INTO Exercises (id, name, muscle_group, description) VALUES
  (gen_random_uuid(), 'Barbell Bench Press', 'Chest', 'Classic compound chest exercise'),
  (gen_random_uuid(), 'Incline Dumbbell Press', 'Chest', 'Targets upper chest'),
  (gen_random_uuid(), 'Dumbbell Flyes', 'Chest', 'Isolation exercise for chest'),
  (gen_random_uuid(), 'Push-ups', 'Chest', 'Bodyweight chest exercise'),
  (gen_random_uuid(), 'Deadlift', 'Back', 'Full body compound exercise'),
  (gen_random_uuid(), 'Pull-ups', 'Back', 'Bodyweight back exercise'),
  (gen_random_uuid(), 'Barbell Row', 'Back', 'Compound back exercise'),
  (gen_random_uuid(), 'Lat Pulldown', 'Back', 'Lat-focused exercise'),
  (gen_random_uuid(), 'Barbell Squat', 'Legs', 'King of leg exercises'),
  (gen_random_uuid(), 'Leg Press', 'Legs', 'Machine-based leg exercise'),
  (gen_random_uuid(), 'Romanian Deadlift', 'Legs', 'Hamstring-focused exercise'),
  (gen_random_uuid(), 'Leg Curl', 'Legs', 'Isolation for hamstrings'),
  (gen_random_uuid(), 'Leg Extension', 'Legs', 'Isolation for quadriceps'),
  (gen_random_uuid(), 'Overhead Press', 'Shoulders', 'Compound shoulder exercise'),
  (gen_random_uuid(), 'Lateral Raises', 'Shoulders', 'Isolation for side delts'),
  (gen_random_uuid(), 'Front Raises', 'Shoulders', 'Front delt isolation'),
  (gen_random_uuid(), 'Face Pulls', 'Shoulders', 'Rear delt and upper back'),
  (gen_random_uuid(), 'Barbell Curl', 'Arms', 'Classic bicep exercise'),
  (gen_random_uuid(), 'Tricep Dips', 'Arms', 'Bodyweight tricep exercise'),
  (gen_random_uuid(), 'Hammer Curls', 'Arms', 'Bicep and forearm exercise'),
  (gen_random_uuid(), 'Tricep Pushdown', 'Arms', 'Cable tricep exercise'),
  (gen_random_uuid(), 'Plank', 'Core', 'Isometric core exercise'),
  (gen_random_uuid(), 'Hanging Leg Raises', 'Core', 'Advanced core exercise'),
  (gen_random_uuid(), 'Russian Twists', 'Core', 'Oblique exercise'),
  (gen_random_uuid(), 'Cable Crunches', 'Core', 'Weighted ab exercise')
ON CONFLICT (name) DO NOTHING;
